title: Mustafa Kutay Ebiclioglu # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data scientist with 4+ years of experience in customer analytics, strategy and marketing and a BA in Economics and Business from Boston University. Previously at Formlabs and Tebra, Inc (both growth stage startups). 
  <br><br>
  Certified in Salesforce, Azure and Databricks.
  <br><br>
  <a href="https://www.linkedin.com/in/mkebiclioglu/">View My LinkedIn Profile</a>
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-4411S6RKSL # your Google Analytics tracking ID here
